<?php


 /**
  * Invite Value Object.
  * This class is value object representing database table Invite
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



class Invite {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    var $id;
    var $code;
    var $createdOn;
    var $userId;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    function Invite () {

    }

    /* function Invite ($idIn) {

          $this->id = $idIn;

    } */


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    function getId() {
          return $this->id;
    }
    function setId($idIn) {
          $this->id = (int)$idIn;
    }

    function getCode() {
          return $this->code;
    }
    function setCode($codeIn) {
          $this->code = $codeIn;
    }

    function getCreatedOn() {
          return $this->createdOn;
    }
    function setCreatedOn($createdOnIn) {
          $this->createdOn = $createdOnIn;
    }

    function getUserId() {
          return $this->userId;
    }
    function setUserId($userIdIn) {
          $this->userId = (int)$userIdIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    function setAll($idIn,
          $codeIn,
          $createdOnIn,
          $userIdIn) {
          $this->id = (int)$idIn;
          $this->code = $codeIn;
          $this->createdOn = $createdOnIn;
          $this->userId = (int)$userIdIn;
    }


    /** 
     * hasEqualMapping-method will compare two Invite instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    function hasEqualMapping($valueObject) {

          if ($valueObject->getId() != $this->id) {
                    return(false);
          }
          if ($valueObject->getCode() != $this->code) {
                    return(false);
          }
          if ($valueObject->getCreatedOn() != $this->createdOn) {
                    return(false);
          }
          if ($valueObject->getUserId() != $this->userId) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    function __toString() {
        $out = $this->getDaogenVersion();
        $out = $out."\nclass Invite, mapping to table Invite\n";
        $out = $out."Persistent attributes: \n"; 
        $out = $out."id = ".$this->id."\n"; 
        $out = $out."code = ".$this->code."\n"; 
        $out = $out."createdOn = ".$this->createdOn."\n"; 
        $out = $out."userId = ".$this->userId."\n"; 
        return $out;
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    
	function __clone() {
        $cloned = new Invite();

        $cloned->setId($this->id); 
        $cloned->setCode($this->code); 
        $cloned->setCreatedOn($this->createdOn); 
        $cloned->setUserId($this->userId); 

        return $cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}
   
?>