<?php


 /**
  * Program Value Object.
  * This class is value object representing database table Program
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */




class Program {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    var $id;
    var $tvChannelId;
    var $title;
    var $description;
    var $begin;
    var $end;

    var $recording;


    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    function Program () {

    }

    /* function Program ($idIn) {

          $this->id = $idIn;

    } */


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    function getId() {
          return $this->id;
    }
    function setId($idIn) {
          $this->id = $idIn;
    }

    function getTvChannelId() {
          return $this->tvChannelId;
    }
    function setTvChannelId($tvChannelIdIn) {
          $this->tvChannelId = $tvChannelIdIn;
    }

    function getTitle() {
          return $this->title;
    }
    function setTitle($titleIn) {
          $this->title = $titleIn;
    }

    function getDescription() {
          return $this->description;
    }
    function setDescription($descriptionIn) {
          $this->description = $descriptionIn;
    }

    function getBegin() {
          return $this->begin;
    }
    function setBegin($beginIn) {
          $this->begin = $beginIn;
    }

    function getEnd() {
          return $this->end;
    }
    function setEnd($endIn) {
          $this->end = $endIn;
    }

    function setRecording($recordingIn) {
    	$this->recording = $recordingIn;
    }
    function getRecording() {
    	return $this->recording;
    }


    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */
    
	function setAll($idIn,
          $tvChannelIdIn,
          $titleIn,
          $descriptionIn,
          $beginIn,
          $endIn,
          $recordingIn = null) {
          $this->id = $idIn;
          $this->tvChannelId = $tvChannelIdIn;
          $this->title = $titleIn;
          $this->description = $descriptionIn;
          $this->begin = $beginIn;
          $this->end = $endIn;
          $this->recording = $recordingIn;
    }


    /** 
     * hasEqualMapping-method will compare two Program instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    function hasEqualMapping($valueObject) {

          if ($valueObject->getId() != $this->id) {
                    return(false);
          }
          if ($valueObject->getTvChannelId() != $this->tvChannelId) {
                    return(false);
          }
          if ($valueObject->getTitle() != $this->title) {
                    return(false);
          }
          if ($valueObject->getDescription() != $this->description) {
                    return(false);
          }
          if ($valueObject->getBegin() != $this->begin) {
                    return(false);
          }
          if ($valueObject->getEnd() != $this->end) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    function __toString() {
        $out = $this->getDaogenVersion();
        $out = $out."\nclass Program, mapping to table Program\n";
        $out = $out."Persistent attributes: \n"; 
        $out = $out."id = ".$this->id."\n"; 
        $out = $out."tvChannelId = ".$this->tvChannelId."\n"; 
        $out = $out."title = ".$this->title."\n"; 
        $out = $out."description = ".$this->description."\n"; 
        $out = $out."begin = ".$this->begin."\n"; 
        $out = $out."end = ".$this->end."\n"; 
        return $out;
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    function __clone() {
        $cloned = new Program();

        $cloned->setId($this->id); 
        $cloned->setTvChannelId($this->tvChannelId); 
        $cloned->setTitle($this->title); 
        $cloned->setDescription($this->description); 
        $cloned->setBegin($this->begin); 
        $cloned->setEnd($this->end); 
        $cloned->setRecording($this->recording);

        return $cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    function getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

?>